services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lists-app
    env_file: .env
    ports:
      - "8085:8082"
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
