// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const autocompleteLists = `-- name: AutocompleteLists :many
SELECT i.id, i.text, p.text AS parent_text
FROM lists.items i
LEFT JOIN lists.items p ON p.id = i.parent_id
WHERE i.user_id = $1
  AND i.is_list
  AND (i.text ILIKE '%' || $2::text || '%' OR $2::text <% i.text)
ORDER BY
    (i.text ILIKE $2::text || '%') DESC,
    word_similarity($2::text, i.text) DESC,
    i.updated_at DESC
LIMIT 8
`

type AutocompleteListsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Query  string    `json:"query"`
}

type AutocompleteListsRow struct {
	ID         uuid.UUID `json:"id"`
	Text       string    `json:"text"`
	ParentText *string   `json:"parent_text"`
}

// Lists at any depth whose title contains the query or is a near miss of it
// (trigram word similarity, so small typos still match). Prefix matches rank
// first, then the closest titles.
func (q *Queries) AutocompleteLists(ctx context.Context, arg AutocompleteListsParams) ([]AutocompleteListsRow, error) {
	rows, err := q.db.Query(ctx, autocompleteLists, arg.UserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutocompleteListsRow{}
	for rows.Next() {
		var i AutocompleteListsRow
		if err := rows.Scan(&i.ID, &i.Text, &i.ParentText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createItem = `-- name: CreateItem :one
INSERT INTO lists.items (user_id, parent_id, text, is_list)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, parent_id, text, is_list, created_at, updated_at
`

type CreateItemParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	ParentID *uuid.UUID `json:"parent_id"`
	Text     string     `json:"text"`
	IsList   bool       `json:"is_list"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (ListsItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.UserID,
		arg.ParentID,
		arg.Text,
		arg.IsList,
	)
	var i ListsItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.IsList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM lists.items
WHERE id = $1 AND user_id = $2
`

type DeleteItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, parent_id, text, is_list, created_at, updated_at FROM lists.items
WHERE id = $1 AND user_id = $2
`

type GetItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (ListsItem, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.UserID)
	var i ListsItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.IsList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAncestors = `-- name: ListAncestors :many
WITH RECURSIVE chain AS (
    SELECT p.id, p.parent_id, p.text, 1 AS depth
    FROM lists.items c
    JOIN lists.items p ON p.id = c.parent_id
    WHERE c.id = $1 AND c.user_id = $2
    UNION ALL
    SELECT p.id, p.parent_id, p.text, chain.depth + 1
    FROM chain
    JOIN lists.items p ON p.id = chain.parent_id
)
SELECT id, text FROM chain
ORDER BY depth DESC
`

type ListAncestorsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListAncestorsRow struct {
	ID   uuid.UUID `json:"id"`
	Text string    `json:"text"`
}

func (q *Queries) ListAncestors(ctx context.Context, arg ListAncestorsParams) ([]ListAncestorsRow, error) {
	rows, err := q.db.Query(ctx, listAncestors, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAncestorsRow{}
	for rows.Next() {
		var i ListAncestorsRow
		if err := rows.Scan(&i.ID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, user_id, parent_id, text, is_list, created_at, updated_at FROM lists.items
WHERE parent_id = $1 AND user_id = $2
ORDER BY created_at, id
`

type ListEntriesParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	UserID   uuid.UUID  `json:"user_id"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListsItem, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListsItem{}
	for rows.Next() {
		var i ListsItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Text,
			&i.IsList,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecent = `-- name: ListRecent :many
SELECT id, user_id, parent_id, text, is_list, created_at, updated_at FROM lists.items
WHERE user_id = $1 AND parent_id IS NULL
ORDER BY updated_at DESC
LIMIT 5
`

func (q *Queries) ListRecent(ctx context.Context, userID uuid.UUID) ([]ListsItem, error) {
	rows, err := q.db.Query(ctx, listRecent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListsItem{}
	for rows.Next() {
		var i ListsItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Text,
			&i.IsList,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevel = `-- name: ListTopLevel :many
SELECT id, user_id, parent_id, text, is_list, created_at, updated_at FROM lists.items
WHERE user_id = $1 AND parent_id IS NULL
ORDER BY lower(text), created_at
`

func (q *Queries) ListTopLevel(ctx context.Context, userID uuid.UUID) ([]ListsItem, error) {
	rows, err := q.db.Query(ctx, listTopLevel, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListsItem{}
	for rows.Next() {
		var i ListsItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Text,
			&i.IsList,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeItemList = `-- name: MakeItemList :one
UPDATE lists.items
SET is_list = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, parent_id, text, is_list, created_at, updated_at
`

type MakeItemListParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MakeItemList(ctx context.Context, arg MakeItemListParams) (ListsItem, error) {
	row := q.db.QueryRow(ctx, makeItemList, arg.ID, arg.UserID)
	var i ListsItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.IsList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchWithAncestors = `-- name: TouchWithAncestors :exec
WITH RECURSIVE chain AS (
    SELECT i.id, i.parent_id FROM lists.items i WHERE i.id = $1
    UNION ALL
    SELECT p.id, p.parent_id
    FROM chain
    JOIN lists.items p ON p.id = chain.parent_id
)
UPDATE lists.items SET updated_at = now()
WHERE id IN (SELECT id FROM chain)
`

func (q *Queries) TouchWithAncestors(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchWithAncestors, id)
	return err
}

const updateItemText = `-- name: UpdateItemText :one
UPDATE lists.items
SET text = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, parent_id, text, is_list, created_at, updated_at
`

type UpdateItemTextParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Text   string    `json:"text"`
}

func (q *Queries) UpdateItemText(ctx context.Context, arg UpdateItemTextParams) (ListsItem, error) {
	row := q.db.QueryRow(ctx, updateItemText, arg.ID, arg.UserID, arg.Text)
	var i ListsItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.IsList,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
